image: docker

services:
  - docker:dind

before_script:
  - apk add --no-cache py-pip
  - pip install docker-compose
  - docker version
  - docker-compose version

stages:
  - test
  - deploy

Unit Tests:
  stage: test
  script:
    - docker-compose run --rm web python manage.py test lists

Func Tests:
  stage: test
  script:
    - docker-compose --project-name functests --file docker-compose.test.yml build
    - docker-compose --project-name functests --file docker-compose.test.yml run testweb
