version: '3.4'
services:
  testweb:
    build: .
    depends_on:
      - firefox
      - chrome-debug
    volumes:
      - .:/usr/src/
    entrypoint: ['./bin/test.sh']
    command: python ./manage.py test functional_tests --parallel
    environment:
      DJANGO_TEST_PROCESSES: 1

  firefox:
    image: selenium/node-firefox:3.14.0-gallium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  chrome-debug:
    image: selenium/node-chrome-debug:3.14.0-gallium
    ports:
      - "5900:5900"
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
      VNC_NO_PASSWORD: 1
      NODE_MAX_INSTANCES: 3
      NODE_MAX_SESSION: 3

  hub:
    image: selenium/hub:3.14.0-gallium
    ports:
      - "4444:4444"
    environment:
      GRID_MAX_SESSION: 6
