version: '3.4'
services:
  web:
    build: .
    volumes:
      - .:/usr/src/
    depends_on:
      - chrome
    environment:
      DJANGO_TEST_PROCESSES: 1
    entrypoint: ["./bin/test.sh"]
    command: python ./manage.py test functional_tests --parallel

  chrome:
    image: selenium/node-chrome:3.14.0-gallium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    ports:
      - "5900:5900"
    environment:
      HUB_HOST: hub
      VNC_NO_PASSWORD: 1

  hub:
    image: selenium/hub:3.14.0-gallium
    ports:
      - "4444:4444"
    environment:
      GRID_MAX_SESSION: 1
