version: '3.4'
services:
  web:
    build: .
    volumes:
      - .:/usr/src/
    ports:
      - "8000:8000"
    entrypoint: ["./bin/entrypoint.sh"]
    command: gunicorn --bind 0.0.0.0:8000 superlists.wsgi
