version: '3.4'
services:
  testweb:
    image: web-django:latest
    depends_on:
      - web
      - firefox
      - chrome-debug
    volumes:
      - .:/usr/src/app
    entrypoint: ['./bin/test.sh']
    command: python ./manage.py test functional_tests

  web:
    build: .
    image: web-django:latest
    entrypoint: ["./bin/entrypoint.sh"]
    command: gunicorn --bind 0.0.0.0:8000 superlists.wsgi
    volumes:
      - .:/usr/src/app
    ports:
      - "8000"

  firefox:
    image: selenium/node-firefox:3.14.0-gallium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  chrome-debug:
    image: selenium/node-chrome-debug:3.14.0-gallium
    ports:
      - "5900:5900"
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
      VNC_NO_PASSWORD: 1

  hub:
    image: selenium/hub:3.14.0-gallium
    ports:
      - "4444:4444"
